### ISSUE TITLE
Długie ładowanie interfejsu

### ISSUE THREAD

**Issue by Netomek** [Fafa87/Domki#105]
Zarówno pod koniec gry, jak i podczas ładowania kolejnej rozgrywki jest długi czas oczekiwania. Podejrzany jest ekran wyników oraz dolny panel wyświetlający statystyki podczas gry.

**Comment by Fafa87** [comment]
Bez grafiki działa szybko i nie zajmuje pamięci.
Bez rycerze_hd zaczyna się ładować i zjadać masę pamięci  1.2GB:
![image](https://user-images.githubusercontent.com/9865688/87858666-d147a200-c92f-11ea-9b3e-aef0fb73f9bb.png)

**Comment by Fafa87** [comment]
Poprawiłem ładowanie stylu:
- przeniosłem do theme
- ustawianie rankingu zrobiłem w pakiecie

**Comment by Fafa87** [comment]
Zlikwidowałem wyciek. Powinno być lepiej, ale nadal trwa to trochę czasu - szczególnie na Debugu.

**Comment by Fafa87** [comment]
Warto do tego wrócić i przekonać się, że naprawdę czcionki zajmują tak dużo miejsca.

**Comment by Fafa87** [comment]
Czcionki zajmują miejsce ponieważ dla każdej kombinacji czcionka + rozmiar generują sobie wszystkie znaki. Szczególnie jest to kosztowne gdy rozmiar jest duży np. 
`Label # Alarm {
    Color: #ffff00ff;
    FontSize: 80;
}`

**Comment by Fafa87** [comment]
Zmieniłem, aby od razu tworzone były tylko znaki ASCII reszta będzie generowana jak będzie potrzebna.
