### ISSUE TITLE
Proste poprawki do interfejsu planety

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#113]
Aktualny interfejs jest uszyty na chama, więc może warto się chwilę zastanowić jak to mogłoby sensowniej działać.

Przyciski Załóż i dołącz powinny albo się wyszarzać albo się podmieniać w zależności od tego czy serwer gry w tym pokoju już stoi.

**Comment by Netomek** [comment]
Podczas pisania, gdy tekst wykracza poza ekran, suwak nie przesuwa się automatycznie na dół, żeby zobaczyć najnowszą napisaną przez siebie, bądź kogoś wiadomość.

**Comment by Netomek** [comment]
Po prawej stronie mogłyby się pojawiać listy oznaczające pokoje. Jak ostatnio sprawdzałem to była jedna lista osób. Pomysł jest taki, aby było kilka takich list jedna po drugiej, z oznaczaniami Pokój nr1, Pokój nr2 itd. W przypadku, gdy w pierwszym pokoju mogą być dwie osoby, to przy dołączeniu trzeciej po prawej stronie pojawia się następna lista z nagłówkiem "Pokój nr 2" i nazwami graczy w tamtym pokoju. Mogłoby to pomóc w zauważeniu, którym osobom nie udało się dołączyć do serwera, a które są w innym pokoju. Poza tym myślę, że chat powinien być bardziej intuicyjny. Gdy ktoś napisze wiadomość, to tekst, który się pojawia powinien się składać z dwóch części w różnych kolorach. Jedna część to nazwa osoby piszącej i dwukropek, a druga to treść wiadomości. Wtedy będę wiedział co napisałem ja, a co ktoś inny. Inny kolor pozwala również na szybsze rozpoznanie autora.

**Comment by Netomek** [comment]
Oczywiście w przypadku tekstu, chcę również widzieć swoją nazwę, bo jest to bardziej intuicyjne, gdy na pierwszy rzut oka widzę co jest moją wiadomością, a co nie.

**Comment by Fafa87** [comment]
1. Jak powinno wyglądać przełączanie się między pokojami? Aktualnie po wpisaniu nowej nazwy pokoju i Enterze przenosi / tworzy się nowy pokój.
2. Pokoje nie mają określonego rozmiaru - nie wszyscy gracze z pokoju muszą grać.

**Comment by Fafa87** [comment]
Fafa87 commented on 18 Nov

**Comment by Fafa87** [comment]
Fafa87 commented  10000000000000000000000000000000000000000000000000000000000000000000000000 seconds ago

**Comment by Fafa87** [comment]
batolek

**Comment by Fafa87** [comment]
dudulek

**Comment by Fafa87** [comment]
podoleta

**Comment by Fafa87** [comment]
Do zrobienia tutaj pozostało kolorowanie tekstu w chacie (aby było widać co jest komunikatem, nazwy graczy lepiej, to co piszą lepiej).

**Comment by Fafa87** [comment]
![image](https://user-images.githubusercontent.com/9865688/116811335-12204880-ab49-11eb-8e8b-e4e229c0048c.png)
