### ISSUE TITLE
Dodanie ? z linkiem do opisu w instrukcji w różnych miejscach

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#116]
Trzeba umożliwić zwykłym śmiertelnikom zostanie:
- mistrzami domków
- graczami lokalnymi
- graczami na planecie

**Comment by Netomek** [comment]
Na razie postaram się opisać na wiki w możliwie jasny i przejrzysty sposób, jak wygląda sterowanie w grze. Samouczek może być świetnym sposobem na naukę korzystania z możliwości jakie daje sterowanie, ale myślę, że potrzebne może być lekkie przeprojektowanie sposoby przekazywania informacji przez Mysz Decydenta. Misja w samouczku musi mieć dostęp do realizacji rozkazów, ponieważ to jest kluczowy element samouczka. Tak samo w przypadku SI, ponieważ nie chcemy, by komputer nic nie robił, ale żeby stanowił pewne zagrożenie dla gracza, mimo to jednak zależy nam, aby gracz miał wolną rękę na zapoznaniu się z grą.

**Comment by Fafa87** [comment]
Ok, niech będzie tam dużo obrazków. 
W takim razie może warto dać linka do wiki bezpośrednio z gry, albo gdzieś osadzić screena z wiki?

**Comment by Fafa87** [comment]
Dorzuciłem linki do wikipedii. Wydaje mi się, że nad wiki trzeba jeszcze popracować, ale jest to dobry początek.
