### ISSUE TITLE
Nie da się postawić punktu kontrolnego z zamku

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#120]

**Comment by Netomek** [comment]
W wersji z trzema kliknięciami punkty kontrolne wymarszu można stawiać tylko z miast. Czy może była możliwość ustawienia punkty ze zbrojowni, a z Zamku już nie? Wtedy rzeczywiście jest to błąd.

**Comment by Fafa87** [comment]
Wydaje się, że tak było zamierzone działanie i jest już zmienione.
