### ISSUE TITLE
Błąd w pewnych przypadkach w nowej wersji

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#123]

**Comment by Fafa87** [comment]
![image](https://user-images.githubusercontent.com/9865688/93430120-76481200-f8c2-11ea-8979-23fb6d89bf01.png)

**Comment by Fafa87** [comment]
![image](https://user-images.githubusercontent.com/9865688/93430490-0b4b0b00-f8c3-11ea-82c0-1958b0875a2d.png)

Wydaje mi się, że to wtedy kiedy zdobywany jest domek tak, że jest zero.

**Comment by Fafa87** [comment]
Może warto to sprawdzić za pomocą testu.

**Comment by Fafa87** [comment]
Ciężko to powtórzyć - raz się jeszcze zdarzyło.

**Comment by Netomek** [comment]
Typ domku ustawiamy przy inicjalizacji, a zmieniamy tylko podczas przebudowy, wiec jest to dziwny błąd. Gra się wyłącza, czy dzieje się coś dziwnego.

**Comment by Fafa87** [comment]
Jak potrafimy powtórzyć to trzeba to wyśledzić.
Prawdopodobnie ten obiekt jest usuwany - dlatego pojawiają się w tym miejscu w pamięci śmieci.

**Comment by Fafa87** [comment]
Widziałem, że usunąłeś szybki przemarsz (374dc7e2d81a8f547320e235efc2c33191126a14). Czy to naprawia problemy?

**Comment by Netomek** [comment]
Po ostatniej aktualizacji sterowania, podczas testowania nie natrafiłem na żadne problemy. W tej poprawce, do której się odnosisz usunąłem szybki przemarsz, bo stwierdziłem, że jest niepotrzebny i wprowadza złą mechanikę. Nie pamiętam teraz czy udało mi się dojść do tego na czym polegał błąd, ale chyba chodziło o to, że ludek, który miał przejść szybkim przemarszem trafiał na większego ludka, który pochłaniał jego ludki. W efekcie próbował(nie udawało mu się?) go usunąć.
