### ISSUE TITLE
Może lista aktualnie utworzonych pokojów powinna się gdzieś pojawiać?

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#126]
Może na życzenie powinna się aktualizować?
Pytanie czy to powinny być wszystkie gry czy tylko gry publiczne - z opcją założenia pokoju prywatnego, który ma hasło albo jest niewidoczny.

**Comment by Netomek** [comment]
Myślę, że pokoje prywatne są istotnym usprawnieniem, ale pytanie czy na tym etapie. Co do opisu listy pokoi, to rozwiązałbym to w ten sposób jaki napisałem w #113 .

**Comment by Fafa87** [comment]
Zgadzam się, pokoje w miejscu gdzie mamy użytkowników.

**Comment by Fafa87** [comment]
```Po prawej stronie mogłyby się pojawiać listy oznaczające pokoje. Jak ostatnio sprawdzałem to była jedna lista osób. Pomysł jest taki, aby było kilka takich list jedna po drugiej, z oznaczaniami Pokój nr1, Pokój nr2 itd. W przypadku, gdy w pierwszym pokoju mogą być dwie osoby, to przy dołączeniu trzeciej po prawej stronie pojawia się następna lista z nagłówkiem "Pokój nr 2" i nazwami graczy w tamtym pokoju. ```

**Comment by Fafa87** [comment]
Dodatkowo warto zrobić aby puste pokoje były usuwane.
