### ISSUE TITLE
Instalacja aplikacji - łatwa z opcją uaktualniania.

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#129]
wix, advancedInstaller, coś bazowo dostępnego z Visual Studio?

**Comment by Fafa87** [comment]
Narazie zrobiłem skrypt PowerShellowy, który ściąga Domki z Githuba i rozpakowuje, a gry jest w katalogu z Domkami to usuwa wcześniej wszystko (aby nie zostały żadne śmieci).

**Comment by Fafa87** [comment]
Są trzy propozycje:
https://marketplace.visualstudio.com/items?itemName=caphyon.AdvancedInstallerforVisualStudio2019
https://marketplace.visualstudio.com/items?itemName=WixToolset.WiXToolset
https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2017InstallerProjects

**Comment by Fafa87** [comment]
Ostro walczę z wixem i wersjonowaniem. Na pewno do zrobienia jeszcze jest:
- [x] poprawa (przetłumaczenie?) tekstów w instalatorze
- [x] ładne obrazki w instalatorze
- [x] docelowa ikona w instalatorze (i jako skrót)
- [x] nowy skrypt do update (sciagnij instalator i uruchom go po cichu)

**Comment by jusdus** [comment]
![domek1](https://user-images.githubusercontent.com/31569661/103895983-8abe4d80-50f1-11eb-81c5-fde162b4cd91.png)
![domek1_tlo](https://user-images.githubusercontent.com/31569661/103895984-8b56e400-50f1-11eb-82e7-6ff8edc275ee.png)
![domek2](https://user-images.githubusercontent.com/31569661/103895986-8b56e400-50f1-11eb-8607-fe4c152fc8e3.png)
![domek2_tlo](https://user-images.githubusercontent.com/31569661/103895987-8b56e400-50f1-11eb-9099-0b75441e5927.png)
![domek3](https://user-images.githubusercontent.com/31569661/103895988-8bef7a80-50f1-11eb-9585-689cad1d5d4c.png)
![domek3_tlo](https://user-images.githubusercontent.com/31569661/103895990-8bef7a80-50f1-11eb-87a0-b9fa5370d09e.png)
![domek4](https://user-images.githubusercontent.com/31569661/103895992-8c881100-50f1-11eb-8742-0abf53a6b34b.png)
![domek4_tlo](https://user-images.githubusercontent.com/31569661/103895994-8c881100-50f1-11eb-86b9-28d155f3dbab.png)

**Comment by jusdus** [comment]
Jakieś sugestie?

**Comment by Fafa87** [comment]
Wybieramy takie z ramką i przezroczystym tłem i czarnym oknem.
