### ISSUE TITLE
Dodanie rozkazu wycofania

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#130]
Aktualnie wycofanie nie odbywa się przez osobny rozkaz.
Aby można było to zrobić w multi to musi to być rozkaz jak każdy inny.

**Comment by Fafa87** [comment]
Prawy klik na domku w multi powoduje śmierć domków?

**Comment by Fafa87** [comment]
Poprawione - trzeba uważać gdy się dodaje coś do obiektów gry - trzeba się zastanowić jak to powinno być przesyłane w multi.

**Comment by Netomek** [comment]
Dodałem rozkaz CofajLudka i zaktualizowałem pozostały kod, aby to mogło działać. Dodatkowo ustawiłem poprawną stronę ludka podczas wymarszu, ponieważ podczas zawracania strona ludka nie zawsze się zgadzała.

**Comment by Fafa87** [comment]
Brakuje obsługi w multi:
- wysyłanie i odbieranie danych w `multi::Serwer::Odbierz()` i `multi::Klient::Wyslij(vector<Rozkaz*> rozkazy)`
- brakuje podpięcia pod rozgrywke na serwerze w `multi::Podepnij(Rozgrywka& rozgrywka, vector<Rozkaz*> rozkazy)`
- schematu pakowania i rozpakowywania w `void save(Archive & archive, ...` `void load(...`

**Comment by Netomek** [comment]
ustawiłem poniższe funkcje rozkazu cofania, analogicznie jak dla innych rozkazów, ale nie wiem w czym jest problem, bo rozkaz nie jest wykonywany.

**Comment by Netomek** [comment]
Rozkaz już działa.
