### ISSUE TITLE
+- zmienia szybkość tylko w grze samemu

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#137]
Aktualnie tworzony jest rozkaz:
- nie jest on wysyłany (ale trzeba dać continue)
- warto też go zignorować lokalnie - inaczej się to zacznie bardzo niefajnie rozjeżdzać

**Comment by Netomek** [comment]
Motyw z klikaniem +/- dodałem na potrzeby testów działania zmian w sterowaniu. Jest to opcja, która można standardowo zablokować.

**Comment by Netomek** [comment]
Lokalnie dodałem warunek, że aby móc korzystać z dynamicznej zmiany prędkości gry, trzeba włączyć oszustwa, które oczywiście w grze na wielu graczy są zablokowane.

**Comment by Fafa87** [comment]
Fajnie zrobione!
