### ISSUE TITLE
Nowa nazwa i tytuł

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#146]
Nazwa Domki jest niegooglowalna.
Dobrym kandydatem jest Domcraft. Potrzeba:
- [x] zmienić nazwę w grze
- [x] stworzyć piekny napis tytułowy
- [x] umieścić obrazek tytułowy w menach gry
- [x] uaktualnić wiki (nazwa i obrazek)

**Comment by jusdus** [comment]
![domki](https://user-images.githubusercontent.com/31569661/103895824-4af76600-50f1-11eb-9d8b-357286ed555e.png)
