### ISSUE TITLE
Domkigate

### ISSUE THREAD

**Issue by Netomek** [Fafa87/Domki#149]
Domki są bardzo waleczne jeśli chodzi o zużywanie zasobów komputera, jak i w przypadku błędu przestają reagować. Czy jest to związane z konstrukcją programu, czy może innymi kwestiami technicznymi?

**Comment by Fafa87** [comment]
Wygląda to tak jakby program wpadł w jakąś nieskończoną pętlę w której ciągle alokuje nowe obiekty. Poprawiłem dwa miejsca w których mogło to mieć miejsce.
