### ISSUE TITLE
Nowy mechanizm przemieszczania ludków - drogi

### ISSUE THREAD

**Issue by Netomek** [Fafa87/Domki#22]

**Comment by Fafa87** [comment]
Chcemy, aby z danego miasta można było wyruszyć tylko do pewnego podzbioru innych miast.
Należy rozszerzyć opis mapy o taką informację. W szczególności można wyróżnić przypadek gdy brak jest tej informacji (np. w starej wersji mapy) wtedy pozwalamy na dowolne podróże.

**Comment by Fafa87** [comment]
Drogi są oznaczane liniami i można tylko po nich przechodzić (jeśli są podane).

**Comment by Fafa87** [comment]
Nowy format pliku z mapą pozwala na to.

**Comment by Fafa87** [comment]
![image](https://user-images.githubusercontent.com/9865688/40589728-f860f82e-61f2-11e8-9014-fff58e8b31a1.png)
