### ISSUE TITLE
Walka ludków przesyłanych pomiędzy dwoma tymi samymi miastami

### ISSUE THREAD

**Issue by Netomek** [Fafa87/Domki#23]

**Comment by Fafa87** [comment]
Należy sprawić aby gdy dwa ludki są blisko siebie to walczą ze sobą (zostaje maksymalnie jeden), gdy jest ich tyle samo to obydwa powinny przestać istnieć.

Dla ogólności można robić to tylko gdy odpowiednia flaga jest włączona.

**Comment by Fafa87** [comment]
Zrobione w 3961007eb6a6a4f9b9a480c60cff340117824a10
