### ISSUE TITLE
Kampania Zamkowa

### ISSUE THREAD

**Issue by Netomek** [Fafa87/Domki#25]
Zamki z rycerzami jako fabuła gry. To jest jednak jedna z opcji, bo ten sposób gry można zastosować w innych uniwersach.

**Comment by Fafa87** [comment]
Trzeba przemyśleć jak wyglądać będzie kampania zamkowiana.

**Comment by Fafa87** [comment]
Powstała już odpowiednia skórka, która została ustawiona na domyślną.

**Comment by Netomek** [comment]
Do kampanii potrzeba fabuły uwzględniającej stopniowe korzystanie z większej ilości opcji, przeciwnika komputerowego, którego poziom będzie odpowiednio dostosowany (lub kilka poziomów trudności stanowiących odrębnych przeciwników w osobnych scenariuszach) oraz istotny jest sposób zapisu kampanii jak i interfejs.

**Comment by Netomek** [comment]
Zmieniam tytuł na "Kampania Zamkowa", ponieważ część związaną z samą fabułą jest już w głównej mierze zrealizowana (skórki i dodatkowe typy + ewentualne zmiany w balansie), a bardziej aktualne zadanie to stworzenie kampanii.

**Comment by Netomek** [comment]
Dodałem mapy (w sumie 8 = 4 demo i 4 kampania). Pograłem trochę i są według mnie w porządku, ale można się zastanowić nad początkowymi liczbami ludków w domkach tak, żeby trudność mapy była odpowiednia.

**Comment by Netomek** [comment]
Kampania jest na takim etapie, że następne poprawki mogą nastąpić dopiero po wprowadzeniu pewnej liczby zmian w grze. Można już grać w misje po kolei na dwóch poziomach o różnej trudności gry.

**Comment by Netomek** [comment]
Dodałem kolejne poprawki, głównie błędów, ale potrzeba je jeszcze potestować, aby określić ich poziom trudności. Ostatnie dwa poziomy są o tyle ciekawe, że w przedostatnim nie można zbyt agresywnie zaatakować, a ostatniego jeszcze nie udało mi się wygrać na trudnym(zastanawiam się nad poziomem kuźni komputera, który jest wyższy od poziomu gracza).
