### ISSUE TITLE
Minimalny mechanizm wyszukiwania załóż dołącz

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#26]
Gra wieloosobowa jest już przetestowana i działa, więc należy ją wprowadzić do głównej aplikacji.

- [x] Dodanie okna wieloosobowej gry: konsola z informacjami, wybór mapy, stwórz, dołącz, wyjdź
- [x] Na stwórz: utwórz serwer, rozsyłaj informacje o jego istnieniu, czekaj na graczu tylu ile jest na planszy
- [x] Na dołącz: sprawdza czy jest gdzieś rozsyłacz i jak tak to próbuje się połączyć
- [x] Uproszczenie mechanizmu konsolowego połączenia i dodanie klarownych komunikatów, aby każdy mógł się połączyć
- [x] Umożliwienie uruchomienia kolejnej gry bez potrzeby resetowania programu

Wszelkie komunikaty idą do konsoli z informacjami.

**Comment by Fafa87** [comment]
- [ ] Uproszczenie mechanizmu konsolowego połączenia i dodanie klarownych komunikatów, aby każdy mógł się połączyć
- [ ] Umożliwienie uruchomienia kolejnej gry bez potrzeby resetowania programu

**Comment by Netomek** [comment]
Czy ostatni cel z pięciu, czyli pierwszy z góry, został zrealizowany?

**Comment by Fafa87** [comment]
Nie, dalej łączymy się poza główną aplikacją.

**Comment by Fafa87** [comment]
Trzeba się tym zająć - jest to priorytet!

**Comment by Fafa87** [comment]
Na początek robimy wersję minimaln, która zakłada tylko jedną grę w sieci.

**Comment by Fafa87** [comment]
Da się już zagrać!
Trochę się wywala i nie zawsze działa, ale da się wygrać.

**Comment by Fafa87** [comment]
Minimalistyczna wersja już jest!
