### ISSUE TITLE
Bezpośrednie połączenie klawiaturowe

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#29]
Ciekawą opcją może być gra na wiele osób na jednym komputerze. Trzeba wymyślić jak można sterować rozgrywką za pomocą klawiatury, a potem umożliwić aby wielu graczy mogło tak grać na raz.

**Comment by Netomek** [comment]
Czy jest możliwe korzystanie z dwóch kursorów na jednym ekranie?

**Comment by Fafa87** [comment]
Istnieją programy np. Pluralinput, które pozwalają na użycie dwóch myszek. Problem może być z wykryciem i powiązaniem ich z graczami.

**Comment by Fafa87** [comment]
Nowy pomysł jest taki aby sterować dowódcą, który może przemieszczać się miedzy domkami i wysyłać armie.

**Comment by Netomek** [comment]
Myślę o modyfikacji sterowania w stylu tylda,1,2,3,4,5 jako burzenie i przebudowa domków. Co do sterowania samą klawiaturą, to myślę, że nie jest coś do zrealizowania.
