### ISSUE TITLE
Generator losowych map

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#33]
Ciekawą opcją będzie automatyczne generowanie losowych (ale chociaż trochę sensownych) scenariuszy.

Wtedy można rozegrać np. 10 rozgrywek i wpływ losowania może być mniejszy niż umiejętności graczy. Innym sposobem wykorzystania tego jest wygenerowanie wielu map, ale zostawienie tylko tych które są fajne.

**Comment by Netomek** [comment]
Interesującym pomysłem jest również stworzenie edytora map pozwalającego każdemu tworzyć mapy według własnego pomysłu, a poza tym można by pomyśleć o jakimś sposobie selekcji i segregacji nowo-utworzonych map.

**Comment by Netomek** [comment]
Aktualnie jest utworzony edytor pozwalający tworzyć mapy. Pomysłem może być generowanie losowych grafów planarnych na bazie parametrów liczby domków, graczy itp.
