### ISSUE TITLE
Pola bez domków

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#40]
Można dodać miejsca w których na początku nie ma domków (jest np. sama flaga). Nie daje ona żadnych ludków ani korzyści.

Budowa domku w tym miejscu jest bardzo kosztowna.

**Comment by Netomek** [comment]
Można to uwzględnić przy okazji robienia własnych/generowania losowych map i ustawiać domyślne typy domków w danych miejscach, a w niektórych przypadkach (po dodaniu parametru dla domku) blokować przebudowę czy też rozbudowę.

**Comment by Netomek** [comment]
W dalszych etapach, kiedy pojawią się bardziej rozbudowane mapy, w przypadku, gdy 2 drogi przecinają się, w miejscu przecięcia można ustawić miejsce przegrupowania, czyli puste pole, na którym ludki tracą liczebność, ale można wysyłać do każdego połączonego domku. W skrócie - coś a la skrzyżowanie.

**Comment by Fafa87** [comment]
Wrzuciłem wstępne (oznaczone jako osada o poziomie 0). Do dociągnięcia:
- [x] max liczba i wzrastanie (ulepszenie i burzenie)
- [ ] przesywanie informacji o polu w grze wieloosobowej

**Comment by Netomek** [comment]
Jeśli ta wiadomość nie została wysłana, to github mi się zepsuł.

**Comment by Netomek** [comment]
Pola powinny już działać jak należy.

**Comment by Fafa87** [comment]
Trzeba jeszcze zrobić / sprawdzić przesyłanie informacji w grze wieloosobowej.

**Comment by Fafa87** [comment]
Wydaje się, że też powinno działać samo - przesyłane są te same rozkazy - burzenie i przebudowa.

**Comment by Fafa87** [comment]
Działa!
