### ISSUE TITLE
Schemat okna z instrukcjami

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#42]
W kampanii (szczególnie na początku) chcemy pokazać użytkownikowe okienko z objaśnieniami zasad gry. 
Np. aby wyruszyć armią kliknij na domek swój a potem na przeciwnika.

Powinno mieć to postać okienka z opisem (formatownym HTMLem) z możliwością osadzenia filmiku (filmik, bo chcemy widzieć kursor).

**Comment by Netomek** [comment]
Można też pomyśleć o jakimś interfejsie podczas rozgrywki, tak żeby okno pokazujące na przykład liczbę ludków czy szybkość produkcji wszystkich domków nie zasłaniało planszy.

**Comment by Fafa87** [comment]
Uporządkowałem mechanizmu gui. Teraz rozdzielam interfejs od samej gry - aby nie zasłaniał.

**Comment by Fafa87** [comment]
Na dole mamy ładne, wydzielone miejsce na gui.
![image](https://user-images.githubusercontent.com/9865688/54468272-319e6080-478b-11e9-9e3b-3a595dbf8da9.png)
