### ISSUE TITLE
Błąd przy ulepszaniu domków

### ISSUE THREAD

**Issue by Netomek** [Fafa87/Domki#44]
Podczas nieudanej próby ulepszania domku, komputer zapamiętuje dwukrotne kliknięcie i czeka na możliwość wykonania ulepszenia do czasu wykonania następnej operacji.

**Comment by Fafa87** [comment]
Możliwe, że możliwe jest też wysłanie ludków przeciwnika gdy akurat zdobywają domek.

**Comment by Netomek** [comment]
Wydaje mi się, że naprawiłem ten błąd, ale pytanie czy to jest, to co chcieliśmy uzyskać. Napisałem, aby po dwukrotnym kliknięciu w ten sam domek, gdy nie można wykonać ulepszania, kursor odznaczał się.

**Comment by Netomek** [comment]
Co do wysyłania ludków przeciwnika, to można dodać sprawdzanie czy domek należy do gracza wykonującego ruch, ale z tego co wiem to w przypadku zdobycia jest on odznaczany.

**Comment by Netomek** [comment]
Załatwiłem tą sprawę...
