### ISSUE TITLE
Liczba ludków podczas gry

### ISSUE THREAD

**Issue by Netomek** [Fafa87/Domki#45]
Niech pokazany będzie pasek, składający się z kolorowych części, które swoją długością będą wizualizować stosunek liczby ludków poszczególnych graczy. 

Przy okazji można zrobić statystykę gry w postaci wykresu przedstawiającego ilość ludków każdego z graczy.

**Comment by Fafa87** [comment]
W pierwszym kroku chcemy dodać funkcję do klasy `Rozgrywka` `SilaGracza(int nr_gracza)`, który zliczy ile dany gracz na w ogóle ludków: domki + chodzące.

**Comment by Fafa87** [comment]
Aktualnie pokazuje tylko liczbę ludków.
