### ISSUE TITLE
Balans ulepszeń i innych rodzajów domków

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#47]
Chcemy wzmocnij ulepszenia rodzajów domków, aby opłacało się ich używać na istniejących mapach.
Mogą one nawet być za mocne, chodzi o to aby zachęcić do eksperymentów.

**Comment by Netomek** [comment]
Myślałem o burzeniu i przebudowie domków i uważam, że burzenie powinno dotyczyć jednego poziomu i mieć koszt np. 25. Co do przebudowy to uważam, że poziom powinien zostać ten sam, ale koszt powinien wynosić koszt ulepszenia na wyższy poziom (przebudowa z 1 na 1 poziom wynosi 50, z 2 100, z 3 200 itd.). Reasumując, myślę, że do gry powinny być 4 klawisze, a mianowicie 'O' - przebudowa na osadę, 'Z' - przebudowa na zamek, 'K' - przebudowa na kuźnię i 'B' - burzenie o jeden poziom. Burzyć można budynki przeciwnika, ale też swoje w przypadku, gdy nie chcemy oddać rozbudowanego budynku(koszt burzenia to zawsze 25, a ulepszanie rośnie wykładniczo).

**Comment by Netomek** [comment]
Wprowadziłem zmiany, ale po nich gra nie działa.

**Comment by Netomek** [comment]
Wprowadziłem część zmian i gra działa.

**Comment by Netomek** [comment]
Załatwiłem sprawę burzenia i przebudowy jak 3 komentarze wyżej. Tym razem wszystko działa.

**Comment by Fafa87** [comment]
Przetestowałem burzenia, działa zgodnie z opisem.
