### ISSUE TITLE
Nowe i stare mapy

### ISSUE THREAD

**Issue by Netomek** [Fafa87/Domki#49]
Dodanie nowych map, jak i również usprawnienie starych, aby zmniejszyć lub zwiększyć dynamikę gry na wielu graczy. Myślałem również o wprowadzeniu map bez możliwości ulepszania, na której są neutralne zamki i kuźnie co spowoduje, że gracze nie będą myśleli nad tym gdzie postawić jaki budynek, ale tylko, który budynek zdobyć.

**Comment by Netomek** [comment]
Dodałem mapę starcie, w której uwzględnione są niektóre własności domków, takie jak poziom czy typ ustawiane przez mapę. W misja.cpp dodałem dodatkowe instrukcje mające na celu czytanie takich własności jak liczebność, typ, poziom czy możliwość ulepszania, bądź przebudowy.

**Comment by Fafa87** [comment]
Mapa starcie jest mega dobra - nie wiadomo która strategia jest najlepsza.
