### ISSUE TITLE
Oznaczenia poziomów domków

### ISSUE THREAD

**Issue by Netomek** [Fafa87/Domki#54]
Napisałem program, który liczy ilość ludków oraz czas potrzebny do ulepszenia na wyższy poziom w zależności od ilości ludków i stwierdziłem, że można by oznaczyć domki do np. 10 poziomu(raczej mało prawdopodobny poziom) ew. np. 7 poziomu. Są to jednak optymistyczne liczby, a poziom 5 powinien wystarczyć.

**Comment by Netomek** [comment]
Podaj poziom docelowy: 
Dla poziomu 1 : 
Maksymalna ilosc ludkow : 100 , a ilosc do ulepszenia : 50
Czas do ulepszania : 50.00 s lub 0.83 min lub 0.01 h 
Dla poziomu 2 : 
Maksymalna ilosc ludkow : 200 , a ilosc do ulepszenia : 100
Czas do ulepszania : 50.00 s lub 0.83 min lub 0.01 h 
Dla poziomu 3 : 
Maksymalna ilosc ludkow : 400 , a ilosc do ulepszenia : 200
Czas do ulepszania : 66.67 s lub 1.11 min lub 0.02 h 
Dla poziomu 4 : 
Maksymalna ilosc ludkow : 800 , a ilosc do ulepszenia : 400
Czas do ulepszania : 100.00 s lub 1.67 min lub 0.03 h 
Dla poziomu 5 : 
Maksymalna ilosc ludkow : 1600 , a ilosc do ulepszenia : 800
Czas do ulepszania : 160.00 s lub 2.67 min lub 0.04 h 
Dla poziomu 6 : 
Maksymalna ilosc ludkow : 3200 , a ilosc do ulepszenia : 1600
Czas do ulepszania : 266.67 s lub 4.44 min lub 0.07 h 
Dla poziomu 7 : 
Maksymalna ilosc ludkow : 6400 , a ilosc do ulepszenia : 3200
Czas do ulepszania : 457.14 s lub 7.62 min lub 0.13 h 
Dla poziomu 8 : 
Maksymalna ilosc ludkow : 12800 , a ilosc do ulepszenia : 6400
Czas do ulepszania : 800.00 s lub 13.33 min lub 0.22 h 
Dla poziomu 9 : 
Maksymalna ilosc ludkow : 25600 , a ilosc do ulepszenia : 12800
Czas do ulepszania : 1422.22 s lub 23.70 min lub 0.40 h 
Dla poziomu 10 : 
Maksymalna ilosc ludkow : 51200 , a ilosc do ulepszenia : 25600
Czas do ulepszania : 2560.00 s lub 42.67 min lub 0.71 h 
Dla poziomu 11 : 
Maksymalna ilosc ludkow : 102400 , a ilosc do ulepszenia : 51200
Czas do ulepszania : 4654.55 s lub 77.58 min lub 1.29 h 
Dla poziomu 12 : 
Maksymalna ilosc ludkow : 204800 , a ilosc do ulepszenia : 102400
Czas do ulepszania : 8533.33 s lub 142.22 min lub 2.37 h 
Dla poziomu 13 : 
Maksymalna ilosc ludkow : 409600 , a ilosc do ulepszenia : 204800
Czas do ulepszania : 15753.85 s lub 262.56 min lub 4.38 h 
Dla poziomu 14 : 
Maksymalna ilosc ludkow : 819200 , a ilosc do ulepszenia : 409600
Czas do ulepszania : 29257.14 s lub 487.62 min lub 8.13 h 
Dla poziomu 15 : 
Maksymalna ilosc ludkow : 1638400 , a ilosc do ulepszenia : 819200
Czas do ulepszania : 54613.33 s lub 910.22 min lub 15.17 h

**Comment by Netomek** [comment]
Co do domków, to można by stworzyć system zmiany prędkości gry w zależności od liczby domków zajmowanych przez gracza. Chodzi o to, aby przy większej liczbie kontrolowanych domków, mieć więcej czasu na ich kontrolę. Myślałem o czymś w rodzaju średniej, aby ten system mógłby być zastosowany w grze wieloosobowej.

**Comment by Netomek** [comment]
Ograniczyłem możliwość ulepszania do 5 poziomu, ale jeszcze będzie trzeba oznaczyć te poziomy, na przykład graficznie.

**Comment by Netomek** [comment]
Chciałbym zmienić nazwy typów budynków, aby były one bardziej precyzyjne i stworzyć skórki do każdego poziomu z tych typów. Mam wstępne rysunki, ale dobrze by było się najpierw spotkać z grafikiem :). Co do typów to chodzi tu przede wszystkim o Miasto zamiast Osada(wygląd jako coraz więcej domków lub większa kamienica), Fort zamiast Zamek(wieże stanowiące jeden budynek), i Zbrojownia zamiast Kuźnia(coś jak kuźnia). Myślałem jeszcze o Wieży i Stajni oraz paru innych, ale to trzy wcześniej wymienione mają większy priorytet.

**Comment by jusdus** [comment]
[zamek.zip](https://github.com/Fafa87/Domki/files/2947401/zamek.zip)

Proszę o ocenę - zamek, poziom 1-5

**Comment by jusdus** [comment]
Zamek jak zamek. Natomiast na pewno lepsze miasto od osady. Myślę jak zaznaczyć rozbudowy kuźni, na miasto mam plan. Ewentualnie jak masz jakieś pomysły, to mi wrzuć (szkic/referencja). Niestety umiejętności grafika nieco kuleją :D

**Comment by Netomek** [comment]
Wysłałem maila, ale coś się chyba zepsuło przez zdjęcia... Zamek jest super!

**Comment by Fafa87** [comment]
Wygląda całkiem fajnie, zrobiłem mechanizm który używa tych poziomów:
(tak, ten zrzut jest gdy nie wrzuciłem 5 poziomu :) )
![image](https://user-images.githubusercontent.com/9865688/54079249-a714b780-42d9-11e9-82d9-55c7e9d19e11.png)

**Comment by Netomek** [comment]
Rozumiem, że wieże na zamku są zawsze czerwone i na razie pokazujemy do kogo należy budynek tylko poprzez ilość ludkowiczów i poziom w odpowiadającym graczowi kolorze?

**Comment by Netomek** [comment]
Poza tym polecam mapę test_wielkosci_budynkow_i_domkow.txt. Tam widać zamki.

**Comment by jusdus** [comment]
Na dysku google pojawiło się miasto.

**Comment by jusdus** [comment]
Na dysku pojawiła się kuźnia/zbrojownia

**Comment by Fafa87** [comment]
Wrzucone.

**Comment by Fafa87** [comment]
Pozostało:
- pole
- stajnia (5 poziomów)
