### ISSUE TITLE
Dodatkowe parametry okna statystyk

### ISSUE THREAD

**Issue by Netomek** [Fafa87/Domki#55]
W lewym dolnym rogu jest okno pokazujące wynik oraz aktualną liczbę ludków każdego z graczy. Ciekawym rozwinięciem mogło by być dodanie parametru produkcji ludków oraz tzw. modernizacji, czyli odpowiednik produkcji dla kuźni.

**Comment by Fafa87** [comment]
Rozszerzyłem test i on pokazuje, że wyliczenie nie zawsze działa - test nie przechodzi.

**Comment by Fafa87** [comment]
Teraz działa, może nie działa na releasie?
