### ISSUE TITLE
Prosty przeciwnik komputerowy

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#6]
Należy napisać prostego Decydenta, który będzie jak prostym przeciwnikiem komputerowym. Na WykonajRuch powinien on podejmować decyzję czy i gdzie wysłać armie.

**Comment by Netomek** [comment]
3 komputerow na mapie i gracz. Mapa jest plikiem tesktowym 4x9 gdzie '.' to puste pole a numery od 1 do 5 to pola grajace z czym 1 to gracz, 5 to neutralne a 2-4 to SI.
