### ISSUE TITLE
Nowe i stare typy budynków

### ISSUE THREAD

**Issue by Netomek** [Fafa87/Domki#60]
Właśnie przeglądam pliki projektu, aby zorientować się w jaki sposób łatwo dodawać nowe budowle i w jaki sposób obsługiwać ich działanie. Poza tym, trzeba poprawić to jak działają stare budowle. Przede wszystkim ilość poziomów oraz ich wpływ na wielkość i wygląd budowli.

**Comment by Netomek** [comment]
Ustawiłem wzrost wielkości domków oraz stworzyłem mapę obrazującą zależność wielkości od liczby ludków i poziomu.

**Comment by Netomek** [comment]
Dodałem nowe typy, a stare nazwy zmieniłem na bardziej precyzyjne. Aktualny model kodu źródłowego wydaje się w porządku i sprawa wygląda na załatwioną.

**Comment by Fafa87** [comment]
Jak załatwione to zamykamy!
