### ISSUE TITLE
Ludki nie walczą

### ISSUE THREAD

**Issue by Netomek** [Fafa87/Domki#62]
Chociaż zdarza się to dosyć rzadko, to psuje to jakość rozgrywki i powinno zostać naprawione.

**Comment by Netomek** [comment]
Przejrzałem kod i sprawa prezentuje się następująco: jeśli wysyłany ludek jest mniejszy od domku, to zanim podejmie walkę ze zbliżającym się wrogiem, domek z którego wychodzi może stykać się z wrogim ludkiem i w efekcie zostać zdobyty.

**Comment by Fafa87** [comment]
Aktualnie zdarza się to nagminnie - grałem w starcie i bardzo często się mijali.

**Comment by Fafa87** [comment]
^ dobra analiza!

**Comment by Netomek** [comment]
Wydaje mi się, że problem już nie występuje po zmianie warunku w funkcji odpowiadającej za walkę.

**Comment by Fafa87** [comment]
Wrzuciłem test pokazujący, że nadal to może występować - możemy to potraktować jako trik - jest to dużo trudniejsze.

**Comment by Fafa87** [comment]
Na razie zamykam, wrócimy gdy problem ponownie okaże się uciążliwy.
