### ISSUE TITLE
Możliwość minimalizacji rozgrywki

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#66]

**Comment by Netomek** [comment]
Leave a comment.

**Comment by Fafa87** [comment]
Aktualnie jest to możliwe gdy gra jest uruchomiona w oknie (w Debugu).

**Comment by Fafa87** [comment]
Gdy gra się na pełen ekran można użyć MS+D, aby na chwilę zobaczyć pulpit.
Na razie wydaje się, że to wystarcza.
