### ISSUE TITLE
Wygląd ludków w zależności od ulepszeń

### ISSUE THREAD

**Issue by Netomek** [Fafa87/Domki#68]
Chcemy, żeby było widoczne, że gracz posiada kuźnię lub stajnię poprzez odpowiedni wygląd. Do kuźni mogli by to być uzbrojeni rycerze, a do stajni rycerze/chopki na koniach.

**Comment by Fafa87** [comment]
Na początek chcemy mieć 3 poziomy chodzących ludków, potem można ich wsadzić na konie :)

**Comment by Fafa87** [comment]
Mechanizm jest gotowy, brakuje tylko:

- [x] rycerze
- [x] chlop na koniu
- [x] szlachta na koniu
- [x] rycerz na koniu

**Comment by Fafa87** [comment]
@jusdus jak się uda to warto dodać rycerzowi piórko i jakąś broń.

**Comment by Fafa87** [comment]
Aktualny stan:
![image](https://user-images.githubusercontent.com/9865688/71602517-0093ee80-2b59-11ea-97b4-629de3675c9d.png)

**Comment by Fafa87** [comment]
![image](https://user-images.githubusercontent.com/9865688/71646898-48984a00-2cee-11ea-8ce6-2f2c5ab15b8f.png)
