### ISSUE TITLE
Sterowanie

### ISSUE THREAD

**Issue by Netomek** [Fafa87/Domki#69]
Parę komitów wcześniej zmieniłem sterowanie klawiaturą z liter na cyfry, a teraz myślę o następnych zmianach sterowania w celu usprawnienia gry. Przede wszystkim, aby burzenie i przebudowa nie odznaczały wybranego domku. Ciekawą opcją byłaby również zmiana sposobu przesyłania ludków. Chodzi o to, aby ludki wysyłać prawym przyciskiem myszy, a wybierać budynki lewym, zakładając, że wybrany domek się nie odznacza. Mam zamiar to skończyć dzisiaj, ale zastanawiają mnie takie aspekty jak na przykład burzenie "od razu", gdy się przytrzyma przycisk burzenia(w przeciwieństwie do przesyłania ludków, "działacz" nie czeka 0.2/0.5 sekund zanim prześle rozkaz).

**Comment by Netomek** [comment]
Można pomyśleć o odznaczaniu się domków po jakimś czasie od braku aktywności.

**Comment by Netomek** [comment]
Gra się o wiele lepiej, chociaż trzeba się przyzwyczaić. Do poprawienia jest jeszcze: ulepszanie, przesyłanie oraz ew. burzenie/przebudowa. Są to raczej mniej istotne dodatki, a główny zarys już jest zrobiony.

**Comment by Netomek** [comment]
Jeśli byśmy zdecydowali się na ten model sterowania, to dobrze byłoby uaktualnić opis pierwszej misji.

**Comment by Fafa87** [comment]
Potrzebny jest przykładowy obrazek, pokazywany na dole, który wyjaśni klawiszologię.

**Comment by Netomek** [comment]
Dodałem komita ze zmianami w sterowaniu, czyli ulepszanie tylko po szybkim klikaniu, szybsze ulepszanie o kilka poziomów i wysyłanie ludków gdy są 3 kliknięcia.

**Comment by Fafa87** [comment]
Działa!
