### ISSUE TITLE
Błąd przesyłu ludków

### ISSUE THREAD

**Issue by Netomek** [Fafa87/Domki#70]
Nie wiem od kiedy jest ten błąd, ale przed uaktualnieniami od Fafy (które raczej nie dotyczyły tego) wszystko działało; z tego, co pamiętam. Chodzi o błąd podobny do tego w multi(tzw. cofanie się ludków, pojawianie w innych miejscach), czyli o takie jakby cofanie w czasie.

**Comment by Fafa87** [comment]
Chodzi o lagi gdy np. zdobywany jest domek. Możliwe, że wynika to z tego, że doczytują się ponownie obrazki?

**Comment by Netomek** [comment]
Jest problem z atakiem, gdy jest duży poziom szybkości (duża liczba poziomów stajni). Czy problemy są powiązane?
