### ISSUE TITLE
Fort na pierwszym poziomie nic nie daje

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#74]

**Comment by Fafa87** [comment]
Powstały nawet na to testy automatyczne (jeden na funkcję policz, a drugi na symulację walki).

**Comment by Netomek** [comment]
To jest błąd? W forcie siła ludków jest równa: liczebność razy poziom fortu (czyli pierwszy poziom nic nie daje).

**Comment by Fafa87** [comment]
Wydawało mi się, że powinien coś dawać, bo inaczej nie ma on sensu (no i dziwnie wygląda, bo niby mury a nic nie dają :) )

**Comment by Netomek** [comment]
Można przesunąć o jeden poziom, czyli fort k-tego poziomu działa jak fort (k+1)-tego poziomu. Nie wiem, czy to nie będzie zbyt silne w porównaniu do na przykład zbrojowni (10 zbrojowni dla fortu na 1 poziomie). Lepszego pomysłu, który nie polegałby na dodaniu nowych właściwości budynku, nie mam.

**Comment by Fafa87** [comment]
Myślę, że warto spróbować.

**Comment by Netomek** [comment]
Wzmocniłem fort o jeden poziom.

**Comment by Netomek** [comment]
Można pomyśleć jeszcze nad wieżą i stajnią, gdzie wieżę można wzmocnić o większy zasięg, a stajnię można osłabić, aby na przykład szybkość nie rosła liniowo, bo przy większej ilości ludki "drgają" wokół celu.
