### ISSUE TITLE
Nie działa uruchamianie wielu rozgrywek w multi

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#77]
Podobnie po zakończeniu pojedyńczej rozgrywki coś abort krzyczy.

**Comment by Fafa87** [comment]
Innym problemem jest to, że kolejna rozgrywka zaczyna się od razu - warto kliknać od razu.

**Comment by Fafa87** [comment]
Wydaje się, że problem jest gdy gracze naraz wcisnąć dołącz. Serwer tego nie znosi.

**Comment by Fafa87** [comment]
Możliwe, że problem występuje tylko gdy próbuje się uruchomić obydwu klientów na jednej maszynie i one sobie przeszkadzają, bo zmieniają usuwają sobie oczekiwanie na porcie.

**Comment by Fafa87** [comment]
Wydaje się w miarę działać, tylko należy ładnie kończyć grę a nie wychodzić przed jej zakończeniem.

**Comment by Netomek** [comment]
Grałem z tatą w multi i ostatnie pare gier było ok, ale z dużej części gier wywalało, czy też klient nie łączył się z serwerem.

**Comment by Netomek** [comment]
Właśnie testowałem grę na dwa komputery i okazało się, że na małym komputerze po naciśnięciu ESC w trakcie gry na wielu, domki już nie działają na multi i trzeba pobierać domki od nowa.

**Comment by Fafa87** [comment]
Wydzielone osobne zadanie na opuszczanie rozgrywki przed końcem #91.
