### ISSUE TITLE
Sterowanie - ciąg dalszy 

### ISSUE THREAD

**Issue by Netomek** [Fafa87/Domki#84]
Jest pomysł na tak zwane ruchy zautomatyzowane czyli aby po np. 3 kliknięciach automatyzować działacza. Początkowo pomysł ten został zastosowany do przegrupowania, a mianowicie aby przy osiągnięciu 10% liczebności wysyłać wszystkie ludki do miejsca przegrupowania. Wpadłem również na pomysł, aby zastosować ten system w stosunku do ulepszania budowli. Jednak, aby był komfort rozgrywki przydałoby się jakieś oznaczenie - np. w postaci jakiejś flagi na domku, czy flagi na drodze, po której idzie przegrupowanie.

**Comment by Netomek** [comment]
Zrobiłem parę zmian i wrzuciłem komita, ale nie działają rozkazy automatyczne... Zrobiłem to korzystając z punktów kontrolnych w domkach, bo wydaje się to być wygodniejsze. Nie wiem co jest źle, a to co zrobiłem wygląda ok...

**Comment by Fafa87** [comment]
Poprawilismy to troche, zostalo usuwanie punktow gdy przejmuje je przeciwnik.

**Comment by Fafa87** [comment]
Można jeszcze zrobić tą funkcję opcjonalną. Parametr przy tworzeniu MyszDecydenta, pochodzący na razie z gui.

**Comment by Netomek** [comment]
Dałem komita, który wprowadził odznaczanie punktów kontrolnych w domkach, gdy już nie można ich ulepszać oraz gdy nie są to miasta. Zwiększyłem czas do nast. kliknięcia z 0.2 na 0.33 i dodałem limit 4 kliknięć.

**Comment by Netomek** [comment]
Zrobiłem coś takiego, że można sterować komputerem.

**Comment by Netomek** [comment]
Sterowanie komputerem jest możliwe, gdy aktywne są oszustwa. Oszustwa wybiera się przed startem misji, bądź kampanii.

**Comment by Fafa87** [comment]
Pozostały do zrobienia dwie rzeczy:
- [ ] Warto dodać opcję prostego usunięcia punktu kontrolnego
- [ ] Punkt kontrolny powinien zostać usunięty gdy przeciwnik przejmuje budynek (nie działa to na multi)
