### ISSUE TITLE
Stworzenie dobrej planszy

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#9]
Należy stworzyć (na sztywno) jedną planszę dla dwóch osób (+ 'gracz' neutralny).  Może to wyglądać na przykład:
x                 n                 y
    n          n    n          n
x                 n                 y

**Comment by Netomek** [comment]
Plansza czytana z pliku 4 w pionie 7 w poziomie gdzie '.' to puste pole, '1' , '2' , '3' to domki nalezace odpowiednio do gracza komputera i neutralne.
