### ISSUE TITLE
Prezentacja punktów kontrolnych 

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/Domki#94]
Chcemy ładnie pokazać zarówno zakolejkowane ulepszenie (domek) jak i wysyłanie ludków (z -> do).

**Comment by Netomek** [comment]
Myślałem, aby zrobić coś jak "korek", czyli linię przerywaną w kształcie okręgu, który kręci się wokół domku zgodnie lub niezgodnie z ruchem wskazówek zegara. W przypadku ulepszania okrąg kręciłby się niezgodnie z ruchem wskazówek, a w przypadku ataku na odwrót, przy czym droga ataku byłaby oznaczona poprzez linię składająca się z ruchomych linii(coś a' la jak w sc2).

**Comment by Fafa87** [comment]
Na razie zrobiłem tak: 
![image](https://user-images.githubusercontent.com/9865688/71599337-c58abe80-2b4a-11ea-9ec2-a937f6d1e335.png)

czyli wszystko robię strzałkami.
